### ISSUE TITLE
Message From Me

### ISSUE THREAD

**Issue by ehsanr1366** [Bahramudin/git_test#1]
I ask my questions here because I could not find an email from you.

I saw your question in the stackoverflow. I was very eager to find out if you managed to solve the problem?
[Your question](https://stackoverflow.com/questions/53397291/is-there-a-way-to-calculate-the-height-of-the-qstandarditem)

I have the same problem as you.
I also have a question, in the image sent by you, to the right of each row there is a small icon to the item expanding or collapsing. How did you put this icon there? And how you managed when the item was expanding or closing.

Thank you very much for guiding me in this regard.

**Comment by Bahramudin** [comment]
@ehsanr1366 I am sorry that I was not replying to your question! OK, I will try to share the code in this repository, so you can go to open the files (headers and source code), you can check the code line by line, and achieve the result, I wrote this code a long time ago, some of the details I am not very clear now, but you can try to understand it by your self.

Have a good luck!

**Comment by ehsanr1366** [comment]
Thank U so much.
